[package]
name = "converter"
version = "0.1.0"
edition = "2024"

[dependencies]
postgres = {  version = "0.X", features = ["with-chrono-0_4"] }
serde = { version = "1.X", features = ["derive"] }
serde_json = "1.X"
zip = "2.X"
