[package]
name = "smart_home_sensor_server"
version = "0.1.0"
edition = "2024"

[dependencies]
smart_home_common = { path = "../smart_home_common" }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
aes = "0.8.X"
log = "0.4.26"
postgres = "0.X"
